// TODO WHEN SERVING GROUP'S MEMEBERS AND CHAT HISTORY USE DATA COMPRESSSION MAY BE ABLE TO SEND MORE MESSAGES IN HISTORY
// ! WHEN SENDING  AGROUP INVITE THE SENDER UUID SHOULD BE THE GROUP ID NOT THE PERSON WHO SENT THE INVITE
