version: "3"

# TODO implement enviroment variables for the front and backend
#* https://www.milanwittpohl.com/projects/tutorials/full-stack-web-app/dockerizing-our-front-and-backend

services:
  frontend:
    build: ./chatroom
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
