version: "3"

services:
  frontend:
    build: ./chatroom
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env.docker

  backend:
    build: ./backend
    ports:
      - "8000:8000"
