services:
  frontend:
    build: ./chatroom
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./chatroom/.env
    volumes:
      - ./chatroom/dist:/chatroom/dist
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./chatroom/dist:/chatroom/dist
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
